# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
#
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{- if .Values.saapi.backendApi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
  name: {{ .Values.saapi.backendApi.name | quote }}
spec:
  {{- if .Values.saapi.backendApi.ingress.className }}
  ingressClassName: {{ .Values.saapi.backendApi.ingress.className | quote }}
  {{- end }}
  rules:
  - {{- if .Values.saapi.backendApi.ingress.host }}
    host: {{ .Values.saapi.backendApi.ingress.host | quote }}
    {{- end }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.saapi.backendApi.name | quote }}
            port:
              name: api-port
        path: /
        pathType: Prefix
{{- end -}}