#
# Copyright 2024-2025 Open Text.
#
# The only warranties for products and services of Open Text and its
# affiliates and licensors ("Open Text") are as may be set forth in the
# express warranty statements accompanying such products and services.
# Nothing herein should be construed as constituting an additional
# warranty. Open Text shall not be liable for technical or editorial
# errors or omissions contained herein. The information contained herein
# is subject to change without notice.
#
# Except as specifically indicated otherwise, this document contains
# confidential information and a valid license is required for possession,
# use or copying. If this work is provided to the U.S. Government,
# consistent with FAR 12.211 and 12.212, Commercial Computer Software,
# Computer Software Documentation, and Technical Data for Commercial Items
# are licensed to the U.S. Government under vendor's standard commercial
# license.
#

{{- if .Values.saapi.backendApi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
  name: {{ .Values.saapi.backendApi.name | quote }}
spec:
  {{- if .Values.saapi.backendApi.ingress.className }}
  ingressClassName: {{ .Values.saapi.backendApi.ingress.className | quote }}
  {{- end }}
  rules:
  - {{- if .Values.saapi.backendApi.ingress.host }}
    host: {{ .Values.saapi.backendApi.ingress.host | quote }}
    {{- end }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.saapi.backendApi.name | quote }}
            port:
              name: api-port
        path: /
        pathType: Prefix
{{- end -}}