# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
#
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.saapi.config }}
data:
  SERVER_SERVLET_CONTEXT_PATH: "{{ .Values.saapi.ingress.path }}"
  ISOL_AUTH_SERVICE_PROTOCOL: http
  ISOL_AUTH_SERVICE_HOST: "{{ .Values.auth.service.name }}"
  ISOL_AUTH_SERVICE_PORT: "{{ .Values.auth.service.port }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PROTOCOL: "{{ .Values.auth.external.protocol }}"
  ISOL_AUTH_SERVICE_EXTERNAL_HOST: "{{ .Values.auth.external.host }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PORT: "{{ .Values.auth.external.port }}"
  ISOL_AUTH_SERVICE_EXTERNAL_PATH: "{{ .Values.auth.external.path }}"
  ISOL_AUTH_SERVICE_REALM: "{{ .Values.auth.realm }}"
  ISOL_AUTH_SERVICE_API_CLIENT: "{{ .Values.auth.apiClient }}"
  ISOL_AUTH_SERVICE_UI_CLIENT: "{{ .Values.auth.uiClient }}"
  ISOL_AUTH_SERVICE_UI_URL: "{{ .Values.auth.uiUrls }}"
  ISOL_AUTH_SERVICE_TOKEN_EXPIRY_TIME: "{{ .Values.auth.tokenExpiryTimeSeconds }}"
  ISOL_AUTH_SERVICE_BASE_REALM_ROLES: "{{ .Values.auth.baseRealmRoles }}"
  SEARCH_ABSTRACTOR_IDOL_HOST: "{{ .Values.saapi.backendIdolHost }}"
  SEARCH_ABSTRACTOR_IDOL_PORT: "{{ .Values.saapi.backendIdolPort }}"
  SEARCH_ABSTRACTOR_IDOL_CONTENT_HOST: "{{ .Values.saapi.backendIdolContentHost }}"
  SEARCH_ABSTRACTOR_IDOL_CONTENT_PORT: "{{ .Values.saapi.backendIdolContentPort }}"
  SEARCH_ABSTRACTOR_API_HOST: "{{ .Values.saapi.backendApi.name }}"
  SEARCH_ABSTRACTOR_API_PORT: "{{ .Values.saapi.backendApi.port }}"
  SEARCH_ABSTRACTOR_HTTP_CACHE_MAX_AGE: "{{ .Values.saapi.httpCacheMaxAge }}"
  SEARCH_ABSTRACTOR_SESSION_API_HOST: "{{ .Values.sessionapi.service.name }}"
  SEARCH_ABSTRACTOR_SESSION_API_PORT: "{{ .Values.sessionapi.service.port }}"
  SEARCH_ABSTRACTOR_SESSION_LICENSOR_HOST: "{{ .Values.sessionapi.licensor.name }}"
  SEARCH_ABSTRACTOR_SESSION_LICENSOR_PORT: "{{ .Values.sessionapi.licensor.port }}"
  ISOL_AUTH_SERVICE_USERS_FILE: "/maven/test-users.yaml"
  SEARCH_ABSTRACTOR_SERVER_ALLOWED_ORIGINS: "{{ .Values.saapi.allowedOrigins }}"
  SEARCHABSTRACTOR_API_SERVICE_DATABASE_HOST: {{ .Values.saapiPostgresql.fullnameOverride | quote }}
  SEARCHABSTRACTOR_API_SERVICE_DATABASE_PORT: {{ .Values.saapiPostgresql.service.port | quote }}
  SEARCHABSTRACTOR_API_SERVICE_DATABASE_USERNAME: {{ .Values.saapiPostgresql.auth.username | quote }}
  SEARCHABSTRACTOR_API_SERVICE_DATABASE_PASSWORD: {{ .Values.saapiPostgresql.auth.password | quote }}
  SEARCHABSTRACTOR_API_SERVICE_DATABASE_NAME: {{ .Values.saapi.storage.dbName | quote }}
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_APPNAME: "searchabstractor_api_service"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: {{ .Values.saapi.storage.maxFileSize | quote }}
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: {{ .Values.saapi.storage.maxRequestSize | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: session-api-postgres-cfg-map
data:
  init_script.sql: |+
    CREATE DATABASE {{ .Values.saapi.storage.dbName }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.saapi.storage.dbName }} to {{ .Values.saapiPostgresql.auth.username }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.saapi.secret }}
data:
  ISOL_AUTH_SERVICE_API_CLIENT_SECRET: "{{ .Values.auth.apiClientSecret | b64enc }}"
  ISOL_AUTH_SERVICE_ADMIN_USER: "{{ .Values.auth.adminUser | b64enc }}"
  ISOL_AUTH_SERVICE_ADMIN_PASS: "{{ .Values.auth.adminPassword | b64enc }}"
