# BEGIN COPYRIGHT NOTICE
# Copyright 2024 Open Text.
#
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sessionapi.name }}

spec:
  replicas: {{ .Values.sessionapi.replicas }}
  selector:
    matchLabels:
      component:  {{ .Values.sessionapi.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.sessionapi.name }}
    spec:
      containers:
        - name: {{ .Values.sessionapi.name }}
          image: {{ include "idol-library.idolImage" (dict "root" . "idolImage" .Values.sessionapi.image) }}
          imagePullPolicy: {{ .Values.sessionapi.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: sa-session-port
          envFrom:
          - configMapRef:
              name: {{ .Values.sessionapi.config }}
          startupProbe:
{{ include "saapi_probe.session.api" . | indent 12 }}
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
{{ include "saapi_probe.session.api" . | indent 12 }}
            failureThreshold: 2
          livenessProbe:
{{ include "saapi_probe.session.api" . | indent 12 }}
            periodSeconds: 60
            failureThreshold: 20
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sessionapi.service.name | quote }}
spec:
  ports:
  - port: {{ .Values.sessionapi.service.port }}
    targetPort: sa-session-port
    name: sa-session-port
  selector:
    component: {{ .Values.sessionapi.name | quote }}
---

{{- if .Values.sessionapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saapi-session-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;

spec:
  {{- if .Values.sessionapi.ingress.className }}
  ingressClassName: {{ .Values.sessionapi.ingress.className | quote }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.sessionapi.ingress.path }}(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.sessionapi.service.name }}
                port:
                  name: sa-session-port
{{- if .Values.sessionapi.ingress.host }}
      host: {{ .Values.sessionapi.ingress.host | quote }}
{{- end }}
{{- end }}
