#
# Copyright 2024-2025 Open Text.
#
# The only warranties for products and services of Open Text and its
# affiliates and licensors ("Open Text") are as may be set forth in the
# express warranty statements accompanying such products and services.
# Nothing herein should be construed as constituting an additional
# warranty. Open Text shall not be liable for technical or editorial
# errors or omissions contained herein. The information contained herein
# is subject to change without notice.
#
# Except as specifically indicated otherwise, this document contains
# confidential information and a valid license is required for possession,
# use or copying. If this work is provided to the U.S. Government,
# consistent with FAR 12.211 and 12.212, Commercial Computer Software,
# Computer Software Documentation, and Technical Data for Commercial Items
# are licensed to the U.S. Government under vendor's standard commercial
# license.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sessionapi.config }}
data:
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_HOST: {{ .Values.saapiPostgresql.fullnameOverride | quote }}
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_PORT: {{ .Values.saapiPostgresql.service.port | quote }}
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_USERNAME: {{ .Values.saapiPostgresql.auth.username | quote }}
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_PASSWORD: {{ .Values.saapiPostgresql.auth.password | quote }}
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_NAME: {{ .Values.saapiPostgresql.auth.database | quote }}
  SEARCHABSTRACTOR_SESSION_SERVICE_DATABASE_APPNAME: "searchabstractor_session_service"